process: dtl_cngg_test
auto_restart: enabled
exe_file_location: "E:\\HAnh\\C++\\dtl_cngg_test.exe"
sender:
  email: "hoanganh@dytechlab.com"
  password: "Dynamic300320"
alert_emails:
  - hoanganh@dytechlab.com